POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:countTokens
accept: */*
content-type: application/json
x-goog-api-key: *** REDACTED ***

{"contents": [{"parts": [{"text": "What time is it?"}], "role": "user"}, {"parts": [{"thoughtSignature": "CtEBAdHtim9KmOL7TwLLLd8M2Gxwbyj1LMU2IWZk0Uj7Q0-0a66TH9Ml2ny0LHPyd3yBum9uGIIR6ilvYUd9QVqELrm4T4toN6jWhxssrgZ2S5xR_SigN4QhaxU2gf-YywjdlXPM5gw-hcmK1EulAf6vHs7NwabCQNQZRX62ILpxjE6L14pibfAfSRI9L_JkjvWFxIRss2EqXpYYPNycwxofyE4qA33SAmZtVg5zLAGxyNDi0GkwOOCT07RyaYzjR6mHQZd692-IPhwdm4uOZhZNxEc=", "functionCall": {"args": {}, "name": "get_time"}}], "role": "model"}, {"parts": [{"functionResponse": {"id": "bdd640fb-0667-4ad1-9c80-317fa3b1799d", "name": "get_time", "response": {"error": "CUSTOM ERROR HANDLER: The function get_time failed with error: The time API is currently offline (error 0xDEADBEEF).. Please inform the user about this error."}}}], "role": "tool"}]}