POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
accept: */*
content-type: application/json
x-goog-api-key: *** REDACTED ***

{"contents": [{"parts": [{"text": "Hello!"}], "role": "user"}]}