POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:countTokens
accept: */*
content-type: application/json
x-goog-api-key: *** REDACTED ***

{"contents": [{"parts": [{"text": "What is 15 plus 27?"}], "role": "user"}, {"parts": [{"functionCall": {"args": {"b": 27, "a": 15}, "name": "add"}, "thoughtSignature": "Ck8BDDnWxycm3H_XRmdrCVEOEFpzOv3GNh3qZcu3hyotsdKpvQ23R4OLj0WT5xp2DEee42BcYJQtROvi2ZOxQVtrTEKWpg06BHccNht6j8gBCs0BAQw51scclxhCrOiSYbb5RNaM2RUdnmdITHyV7UtpR0dV-YDymy4bCNGmfo4kytBdTpokaRjzGyYjqK8e8C0N5_FUs164_cK2xM0KghZccG5VJgXLBRHc4nFZXCTE36wHaBOsRDwANeiHGL07Rrfdt3NdvKfMI0VjHciYHQRETb6eopwCxLdK2iSaXPv-Ai56Jo9DUOJk11Cl9kkUCjHY2J0HqaJ0zD_41CwixnGMd2L31lCLjJTv8Ow8qmraUGkMh1xohvlV-jNLRvbkMAouAQw51sctGcCAvoY2ii3KSxVAQSe1PJU89pX0bScvez09iEyXEvIKW317lZZnMw=="}], "role": "model"}, {"parts": [{"functionResponse": {"id": "00000000-0000-0000-0000-000000000001", "name": "add", "response": {"result": "42"}}}], "role": "tool"}]}