POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:countTokens
accept: */*
content-type: application/json
x-goog-api-key: *** REDACTED ***

{"contents": [{"parts": [{"text": "What time is it?"}], "role": "user"}, {"parts": [{"functionCall": {"args": {}, "name": "get_time"}, "thoughtSignature": "CsEBAQw51seeHctATS1IRK709aFtGmzvFU0Wi8gDVT-fvrmdnTmSqJqxRfYtzzRrfE4GFykL75c0ZEwJFrdYdwPSLmNsdOa4suJnwOzHZeWc2c287ConWk9LFixv-1nvXHCB-dFDxsg0qiKTsXxFTBI0zac2SyfYA83IjhT8uo_NqLRpU-ESQrt8GWDrcMGAb9L9IacMxkVOq-CeV4tsCIKi7_KA82fFD8U6GT8AuropoqIQtRUNB5LVQ-b1JWbWCvzRmA=="}], "role": "model"}, {"parts": [{"functionResponse": {"id": "00000000-0000-0000-0000-000000000001", "name": "get_time", "response": {"error": "CUSTOM ERROR HANDLER: The function get_time failed with error: The time API is currently offline (error 0xDEADBEEF).. Please inform the user about this error."}}}], "role": "tool"}]}