POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:countTokens
accept: */*
content-type: application/json
x-goog-api-key: *** REDACTED ***

{"contents": [{"parts": [{"text": "What is 15 plus 27?"}], "role": "user"}, {"parts": [{"functionCall": {"args": {"b": 27, "a": 15}, "name": "add"}, "thoughtSignature": "CvsBAQw51seycZ0-X6uJTwKcP3pbuDAJiGYXl_MknOrxaLDke4Mur6VKENyVYy-ZtPUbwYBXakjlYXGjeBSWSIddn_akxTAq3d2FNkYOHvPfLIUbsK6-7GmbUL1zhVwk7RT7b9ED7PD8q3VQ_BxZDMogQU60HHrV6xpCIp9_DUTz_ytn4aDhXwyaVPtSFYWzLun3dbFqQcavkJMy66gsZue1uOaD9c2VaqeeLlwDejW7gRMhbMctZrG5zG36bTbWSe3JelSmnDonFsANs1ToEJHtvLQt1n6K18OXAtc6tPEZYy0JA7VTODdakeDq1h3pJPG3z4VflDMFsS-joWM="}], "role": "model"}, {"parts": [{"functionResponse": {"id": "00000000-0000-0000-0000-000000000001", "name": "add", "response": {"result": "42"}}}], "role": "tool"}]}