POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:countTokens
accept: */*
content-type: application/json
x-goog-api-key: *** REDACTED ***

{"contents": [{"parts": [{"fileData": {"fileUri": "https://generativelanguage.googleapis.com/v1beta/files/m59laraawa5n", "mimeType": "image/png"}}, {"text": "What building is this an image of, and what city was it taken in?"}], "role": "user"}]}