POST https://api.anthropic.com/v1/messages/count_tokens
accept: application/json
content-type: application/json
x-api-key: *** REDACTED ***

{"messages":[{"role":"user","content":[{"type":"text","text":"You are a helpful calculator assistant. Use the provided functions to answer math questions."}]}],"model":"claude-haiku-4-5","tools":[{"name":"add","description":"Add two numbers together.","input_schema":{"properties":{"a":{"type":"integer"},"b":{"type":"integer"}},"required":["a","b"],"title":"add","type":"object"}},{"name":"divide","description":"Divide two numbers.","input_schema":{"properties":{"a":{"type":"number"},"b":{"type":"number"}},"required":["a","b"],"title":"divide","type":"object"}},{"name":"multiply","description":"Multiply two numbers together.","input_schema":{"properties":{"a":{"type":"integer"},"b":{"type":"integer"}},"required":["a","b"],"title":"multiply","type":"object"}}]}