POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:countTokens
accept: */*
content-type: application/json
x-goog-api-key: *** REDACTED ***

{"contents": [{"parts": [{"text": "thank you"}], "role": "user"}, {"parts": [{"text": "arigato"}], "role": "model"}, {"parts": [{"text": "good morning"}], "role": "user"}, {"parts": [{"text": "ohayo"}], "role": "model"}, {"parts": [{"text": "crab"}], "role": "user"}]}